# Práctica 1: Regresión Lineal 

## Parte 1 : Regresión lineal con una variable

_**Autores: Alberto Pastor Moreno e Iván Fernández Mena**_

## 1.1 Carga de datos

En la práctica uno se va a trabajar la regresion lineal con una variable a partir de los datos almacenados en un archivo csv que se nos proporciona. Los datos extraidos estan separado en dos columnas y representan los beneficios de una compañia de distribución de comida en distintas ciudades en base a su población.

In [1]:
from pandas.io.parsers import read_csv
import numpy as np

Definimos un método que lee y carga los datos de un csv y retorna esta información recopilada. Se dicta que en el archivo no hay información de cabecera (header = None) y que los valores que son devueltos son de tipo flotantes.

In [2]:
def load_csv(filename):
    values = read_csv(filename, header=None).values
    return values.astype(float)

In [ ]:
dataset = load_csv('./datasets/ex1data1.csv')

Utilizamos el conjunto de datos obtenido del csv con la función especificada previamente y separamos cada columna en vectores diferentes para poder gestionarlos de manera independiente, de este modo de puede usar cada columna para su estudio.

In [ ]:
independent_data = dataset[:,0]
dependent_data = dataset[:,1]

## 1.2 Visualización simple de dataset 

A continuación se generará un plotter con los datos que previamente tratados. Se creará un plotter de cruces enfrentando los valores de beneficios de la empresa estudiada y la población que se nos ha proporvionado en el dataset.

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.figure()
plt.plot(independent_data, dependent_data, 'rx')
plt.ylabel('Ingresos en $10.000s')
plt.xlabel('Poblacion de la ciudad en 10.000s')

## 1.3 Método de descenso gradiente

Para encontrar la regresión lineal que más se adapte a nuestro dataset, es necesario realizar operaciones básicas de modo que en cada una de las iteraciones se obtenga un resultado más cercano al óptimo. Se necesita definir la función de coste y la función de gradiente de descenso que nos permitira obtener este resultado.

Siempre se tiene que tener en cuenta la función que se usará como hipótesis, en nuestro caso se trata de una unica variable y de una recta.

### - Implementación de la función de hipótesis de la regresión lineal 

In [ ]:
def hyphotesis_function(th0, th1, x):
    return th0 + th1*x

### - Implementacion de la funcion de coste de la regresion lineal J($\theta_0$,$\theta_1$)

In [ ]:
def cost_function(fun, th0, th1, m, x, y):
    sum_cost = 0
    for i in range(0, m):
        sum_cost += (fun(th0, th1, x[i]) - y[i])**2
    cost = sum_cost / (2*m)
    return cost

### - Implementación de función _gradient descent_

In [ ]:
def gradient_descent(fun, th0, th1, m, x, y, lr=0.01, epochs=1500):
    cost = []
    vc_th0 = []
    vc_th1 = []
    curr_th0 = th0
    curr_th1 = th1
    for i in range(0, epochs):
        new_th0 = curr_th0 - (lr/m)*np.sum([fun(curr_th0, curr_th1, x[j]) - y[j] for j in range(0, m)])
        new_th1 = curr_th1 - (lr/m)*np.sum([((fun(curr_th0, curr_th1, x[j]) - y[j])*x[j]) for j in range(0, m)])
        curr_th0 = new_th0
        curr_th1 = new_th1
        epoch_cost = cost_function(fun, curr_th0, curr_th1, m, x, y)
        cost += [epoch_cost]
        vc_th0 += [curr_th0]
        vc_th1 += [curr_th1]
        #print('It: {}, Cost: {}'.format(i, epoch_cost))
    return curr_th0, curr_th1, cost, vc_th0, vc_th1 

A continución se muestran las variables que se han usado para la gestión de la práctica, de este modo se pueden cambiar paramentros de las pruebas de forma comoda. 

In [ ]:
th0 = 0
th1 = 0
lr = 0.01
m = len(dataset)

## 1.4 Resultados obtenidos del estudio

Se aplican las funciones definidas previamente y se muestran los resultados para poder tomar unas conclusiones concretas. Se ejecuta la función de gradiente de descenso en nuestra función de hipótesis, además de toda la información necesaria gestionada y obtenida de nuestro conjunto de datos.

In [ ]:
gd_th0, gd_th1, gd_cost, vc_gd_th0, vc_gd_th1 = gradient_descent(hyphotesis_function, th0, th1, m, independent_data, dependent_data, lr)
print ('th0:{}, th1:{}, cost:{}'.format(gd_th0, gd_th1, gd_cost[-1]))

Como se estudia en los datos mostrados previamente y en la gráfica que se genera posteriormente, se observa que nuestro valor de coste va disminuyendo según se aplica el descenso de gradiente.

In [ ]:
plt.plot(gd_cost)
plt.title('Coste por iteración en el método gradient_descent()')
plt.ylabel('Cost')
plt.xlabel('num_epoch')

Finalmente se muestra el resultado de manera coherente enfrentando los valores del dataset original y los datos obtenidos de ejecutar nuestra función gradiente sobre esos datos.

### Visualización en plotter normal

In [ ]:
plt.plot(independent_data, dependent_data, 'rx', independent_data, hyphotesis_function(gd_th0, gd_th1, independent_data))
plt.title('Recta resultado gradient_descent()')
plt.ylabel('Ingresos en $10.000s')
plt.xlabel('Poblacion de la ciudad en 10.000s')

El resultado es una recta que se encuentra ajustada lo máximo posible para nuestro conjunto de datos, esta recta tiene la separación mínima entre los puntos y la resta, obtenido gracias a la función descenso de gradiente.

### Visualización en plotters 3D

In [ ]:
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter

In [ ]:
fig = plt.figure()
ax = fig.gca(projection='3d')

X, Y = np.meshgrid(vc_gd_th0, vc_gd_th1)
R = np.sqrt(X**2 + Y**2)
Z = np.cos(R)

ax.plot_surface(X, Y, Z, cmap=cm.coolwarm, linewidth=0, antialiased=False)
plt.xlabel('Th0')
plt.ylabel('Th1')

In [ ]:
def f(x, y):
    return np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)

X = np.arange(-10, 10, 0.1)
Y = np.arange(-1, 4, 0.1)

X, Y = np.meshgrid(X, Y)
Z = f(X,Y)

plt.contour(X, Y, Z ,np.logspace(-2, 3, 20), colors='black')
plt.plot(vc_gd_th0[::150], vc_gd_th1[::150], 'rx')

## Parte 2 : Regresión lineal con dos variables



## 2.1 Carga y normalización datos

En esta sección, realizaremos regresión lineal con múltiples variables utilizando un dataset diferente al utilizado en la sección anterior. Por ello, realizamos una nueva carga

In [3]:
dataset = load_csv('./datasets/ex1data2.csv')
nfeatures = 2
dataset[:5]

array([[2.104e+03, 3.000e+00, 3.999e+05],
       [1.600e+03, 3.000e+00, 3.299e+05],
       [2.400e+03, 3.000e+00, 3.690e+05],
       [1.416e+03, 2.000e+00, 2.320e+05],
       [3.000e+03, 4.000e+00, 5.399e+05]])

In [4]:
features = dataset[:,:nfeatures]
target = dataset[:,nfeatures]
features.shape

(47, 2)

Normalizamos los datos los datos de las variables características ya que las unidades utilizadas en el dataset utilizado varían en función al atributo en cuestión. Esto podría generar problemas por lo que sustituimos cada valor de X por su división entre su diferencia con la media de su columna y la desviación estándar de su columna, teniendo en cuenta que cada columna se corresponde con una variable característica en cuestión. 

Esto queda expresado por: $x_i \leftarrow \frac{x_i - \mu}{\sigma_i}$

In [5]:
def normalice(x):
    mu = [np.mean(x[:,i]) for i in range(0,len(x[0]))]
    sigma = [np.std(x[:,i]) for i in range(0,len(x[0]))]
    xnorm = (x - mu)/sigma
    return xnorm, mu, sigma

In [6]:
features_norm, mu, sigma = normalice(features)
ones = np.ones([len(features),len(features[0])+1])
ones[:,1:] = features_norm
features_norm = ones
features_norm[:3]

array([[ 1.        ,  0.13141542, -0.22609337],
       [ 1.        , -0.5096407 , -0.22609337],
       [ 1.        ,  0.5079087 , -0.22609337]])

Definimos los parámetros que utilizaremos en el cálculo _gradient descent_

In [7]:
th = np.array([1,1,1])
lr = 0.01
m = len(dataset)

## 2.2 Función hipótesis

Debido a que tenemos más de una variable característica, en este caso utilizaremos una función definida de la siguiente forma:

$ h_\theta(x)= \theta^T x$

In [8]:
hyphotesis_function = lambda th,x : np.dot(x, th)

In [9]:
hyphotesis_function(th, features_norm[0,:])

0.9053220544433592

## 2.3 Función coste

La función de coste (debajo) queda definida por la siguiente expresión:

$ J(\theta) = \frac{1}{2m}(X\theta - \vec{y})^{T}(X\theta-\vec{y}) $

In [10]:
def cost_function(fun, th, m, x, y):
    cost = (x.dot(th) - y).T.dot(x.dot(th) - y)  / (2*m)
    return cost

In [11]:
cost_function(hyphotesis_function, th, m, features_norm, target)

65591047222.902596

## 2.4 _Gradient descent_

La función _gradient descent_ (debajo) actualiza los valores de $\theta_j$ _epochs_ veces siguiendo la siguiente expresión:

$\theta_j := \theta_j - \alpha\frac{1}{m}\sum_{i=1}^{m}(h_{\theta}(x^{(i)}) - y^{(i)}){x_{j}^{(i)}}$

In [49]:
def gradient_descent(fun, th, m, x, y, lr=0.01, epochs=1500):
    cost = []
    curr_th = th
    for e in range(0, epochs):        
        curr_th = curr_th - (1/m)*lr*(np.dot(x.T, fun(th, x) - y))
        epoch_cost = cost_function(fun, curr_th, m, x, y)
        cost += [epoch_cost]
        #print('It: {}, Cost: {}'.format(e + 1, epoch_cost))
    return curr_th, cost   

In [48]:
gd_th, gd_cost = gradient_descent(hyphotesis_function, th, m, features_norm, target, lr=0.0004)
gd_th

array([204247.99574468,  63458.54411537,  32825.3570732 ])

## 2.5 _Normal Equation_

De forma alternativa a _gradient descent_, planteamos la expresión de la ecuación normal que resuelve los valores de $\theta$ siguiendo la siguiente expresión:

$\theta = (X^{T}X)^{-1}X^{T}\vec{y}$

In [23]:
ones = np.ones([len(features),len(features[0])+1])
ones[:,1:] = features
features_wones = ones
features_t = np.transpose(features_wones)
th_norm_eq = np.dot(np.dot(np.linalg.pinv(features_t.dot(features_wones)), features_t), target)
print (th_norm_eq)

[89597.90954361   139.21067402 -8738.01911255]


### Resultados

Para comprobar que el modelo implementado utilizando _gradient descent_ es correcto, realizamos una predicción con los valores obtenidos de $\theta$ con nuestra implementación y los valores obtenidos con la ecuación normal

In [46]:
x_test = [1, 1650, 3]
x_test[1:] = (np.array(x_test[1:]) - mu ) / sigma
print('Predicción gradient descent:{}, predicción ecuación normal:{}'.format(hyphotesis_function(gd_th, x_test),
                                                                            hyphotesis_function(th_norm_eq, x_test)))

Predicción gradient descent:168521.10623406913, predicción ecuación normal:91511.42364428427
